### ISSUE TITLE
App crashes when trying to print

### ISSUE THREAD

**Issue by jsavagesr** [alunbestor/Boxer#113]
I click on print. i start to warm up the nozzle and bed. the app then creates the gcode then the app closes or crash. 
ROBO R1 printer. just updated  Matter Hackers 1.7 to new app 2.0. The 1.7 worked just fine.
Windows 10, 64bit

**Comment by MaddTheSane** [comment]
This isn't even a Windows program, much less a 3D printer driver.

**Comment by jsavagesr** [comment]
When I bought the ROBO R1 years ago it came with Matter Hackers 1.7 software for windows. The software showed that their is an update. After all this time I finally clicked on it. It loaded just fine. Also I called Matter Hackers and asked them if what I updated to is for Windows. the answer was yes. I was also told that maybe my laptop doesn't meet the minimum requirements.

**Comment by markicus** [comment]
As @MaddTheSane mentioned, this is not the project for Matter Hackers. It is not related to 3D printing at all, so you won’t be finding resolution to your issue here. Good luck on your printing issues, though!

**Comment by jsavagesr** [comment]
Did I say Matter Hackers. I mean to say Matter Control. Thats the name of the software made by Matter Hackers.

**Comment by JoshuaPettus** [comment]
And,again, not this project...this is a dos emulator for MacOS
