### ISSUE TITLE
Retro rendering style broken on MacBookAir6,2

### ISSUE THREAD

**Issue by isrob** [alunbestor/Boxer#29]
I'm on a MacBookAir6,2 running OS X 10.9 and in Privateer (GOG version) the choice of 'Rendering style: Retro' results in a black screen (music continues, no crash, just no visible graphics).

Let me know what further info would be helpful.

**Comment by hexagonstar** [comment]
I know topic is old but the bug still persists on games purchased on GOG.com. Is there any way to address this issue (without having to recompile Boxer/etc.)? I, too, have a Macbook Pro 2013 with Intel HD Graphics 4000. Retro shader results in black screen. Can anyone past a screenshot of how the retro shader looks? Of what I read is that it looks really good (better than scanlines in Boxer standalone)?

**Comment by alunbestor** [comment]
A quick fix would be to copy the fixed shader file into one of the GOG apps you have. The necessary file is here:
https://raw.githubusercontent.com/alunbestor/Boxer/master/Resources/Shaders/crt-geom-interlaced-curved.shader

*(Github makes it awkward to just straight-up download files, so in Safari: right-click on the link above and choose "Download linked file", then rename the resulting file's extension from ".shader.txt" to just ".shader".)*

Once you've downloaded it, right-click on a GOG game in Finder and choose "Show Package Contents". Browse to `Contents/Resources/Shaders/` and replace the file in there with the new one.

Let me know if the shader works correctly for you!

**Comment by hexagonstar** [comment]
that did the trick, thanks! I had the impression the shader needs to be compiled but that's not the case.

The monitor curving is a bit exaggerated on the Retro shader, though. Do you know which values to change to reduce this? I changed R which seems to do that but the graphics then seem to extend outside the visible screen area.

**Comment by alunbestor** [comment]
Smaller R values should reduce the curvature, kinda surprised it makes it extend further outside the frame. You could try lowering the overscan amounts as well to compensate; or increase D, the distance-of-viewer-to-screen, which should flatten the perspective but might have further knock-on effects.
