### ISSUE TITLE
[Game compatibility] Conquests of Camelot: The Search for the Grail

### ISSUE THREAD

**Issue by stephenyeargin** [alunbestor/Boxer#54]
Abandonware game from Sierra. The follow-up title (Conquests of the Longbow) works great with Boxer. This one seems to have trouble with the video drivers. It looks like it has worked at some point with raw DOSBox, but I ran into the same issues.

### Reproduction steps

1. [Download](http://www.christymarx.com/writing/camelotfiles.htm) from the game's creator
2. Unzip
3. Import into Boxer
4. Run installer

The following are the screenshots for each step of the Installer. I've run just about every permutation of them and have not been able to get past the video card driver issue. In some cases, I can get to a flashing underscore (like it is doing something), but it 

![screen shot 2015-01-04 at 12 35 21 am](https://cloud.githubusercontent.com/assets/80459/5605010/c8b35dee-93a9-11e4-8c9a-4965c8de8cd4.png)
![screen shot 2015-01-04 at 12 35 25 am](https://cloud.githubusercontent.com/assets/80459/5605011/c8b5617a-93a9-11e4-87c6-3947dad0fa47.png)
![screen shot 2015-01-04 at 12 35 34 am](https://cloud.githubusercontent.com/assets/80459/5605012/c8b8ec32-93a9-11e4-92ed-d26a841a7208.png)
![screen shot 2015-01-04 at 12 36 14 am](https://cloud.githubusercontent.com/assets/80459/5605015/c8bd46ce-93a9-11e4-8f28-7ec1affe3a88.png)
![screen shot 2015-01-04 at 12 36 19 am](https://cloud.githubusercontent.com/assets/80459/5605013/c8ba3a60-93a9-11e4-999a-8a4f748da40f.png)
![screen shot 2015-01-04 at 12 36 23 am](https://cloud.githubusercontent.com/assets/80459/5605014/c8bb5db4-93a9-11e4-99de-03405a09c576.png)
![screen shot 2015-01-04 at 12 36 28 am](https://cloud.githubusercontent.com/assets/80459/5605016/c8f7387a-93a9-11e4-9670-a963c8d7ada5.png)
![screen shot 2015-01-04 at 12 36 33 am](https://cloud.githubusercontent.com/assets/80459/5605018/c8fbb17a-93a9-11e4-83b6-80ca0804bbb3.png)
![screen shot 2015-01-04 at 12 36 44 am](https://cloud.githubusercontent.com/assets/80459/5605017/c8fa2e18-93a9-11e4-8361-faed854e9aa7.png)

**Comment by alunbestor** [comment]
Conquests of Camelot works fine in Boxer, and I've tested just now using the version from Christy Marx's website you linked. The installer has a few gotchas though:

- The 'preferred' graphics option, "CGA with RGB monitor - 2 colors", should be ignored; the one you want is actually "EGA/VGA with RGB monitor - 16 colors". (Sierra's installers of this era often mis-recommend the graphics option this way.)
- After that, choose "AdLib" as the sound option, or "Roland MT-32" if you have added the necessary ROMs to Boxer (highly recommended.)
- Choose the default options for the remaining questions, then press ESC when asked where you want to install the game (it's already installed and this step is unnecessary).

**Comment by stephenyeargin** [comment]
:+1: Perfect. That last step (of skipping where to install the game) seems to be the biggest issue.

**Comment by alunbestor** [comment]
Yeah, it's a common gotcha with DOS games that the installer will continue to present a copy-files-to-hard-disk option which no longer works after the game has *already* been installed to the hard disk (which is the state most abandonware DOS games are in when you download them.)
