### ISSUE TITLE
Wrong system prefs pane opened on Yosemite

### ISSUE THREAD

**Issue by getaaron** [alunbestor/Boxer#55]
When enabling Universal Access:

![screen shot 2015-01-08 at 10 57 21 pm](https://cloud.githubusercontent.com/assets/789577/5675339/c76ae1c6-9789-11e4-87f3-cff33fbf1ed3.png)

This button opens the Accessibility pane. However, on OS X Yosemite, the preference is under Security & Privacy -> Privacy.

**Comment by alunbestor** [comment]
This issue is covered by https://github.com/alunbestor/Boxer/issues/30. The bug has been fixed in the development branch.

**Comment by getaaron** [comment]
@alunbestor Thanks. I didn't see a commit associated with that issue, nor do I see a development branch. (I only see `master`, `leopard_legacy`, and `standalone`.)
