### ISSUE TITLE
Additional shaders?

### ISSUE THREAD

**Issue by almeath** [alunbestor/Boxer#88]
Is it possible to manually add additional shaders? I looked inside the .shader files and they appear to use GLSL code from shaders with the .glsl file extension. 

It looks like it could be possible, but would take substantial manual editing, rather than being just a drag and drop process.

**Comment by gphilipp** [comment]
@almeath @MaddTheSane I can see the list of shaders under `resources/Shaders` but how do you switch shaders besides the default `CRT Geom` one?

**Comment by gphilipp** [comment]
Nevermind, I found out that the shader selection is hard coded in https://github.com/MaddTheSane/Boxer/blob/maddsV2/Boxer/Metal%20Rendering/BXMetalRenderingView.m#L121
